# config.yml

file_extensions:
  edf: application/x-edf
  cbf: application/x-cbf
  fits: application/x-fits

trees:
  - path: /
    tree: tiled.catalog:from_uri
    args:
      uri: $PATH_TO_DATA_CATALOG #./tiled/db/catalog.db
      writable_storage: /data
      readable_storage: [/data]
      #[/Users/wiebke/Documents/Data/saxs-waxs-samples/desy]
      init_if_not_exists: true
      adapters_by_mimetype: 
        application/x-cbf: custom.cbf:read
        application/x-edf: custom.edf:read
        application/x-fits: custom.fits:read
        application/x-gb: custom.gb:read
        multipart/related;type=application/x-hdf5: custom.lambda_nxs:read_sequence


uvicorn:
  host: 0.0.0.0
  port: 8888


authentication:
  # For local testing allow anonymous access
  allow_anonymous_access: true
  single_user_api_key: ${TILED_API_KEY}
